name: RenderSettings
type: classes
summary:
description:
code_samples:
inherits:
tags:
constructors:
properties:
  - name: ambientEquatorColor
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: DataType.Color
  - name: ambientGroundColor
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: DataType.Color
  - name: ambientIntensity
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: ambientLight
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: DataType.Color
  - name: ambientSkyColor
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: DataType.Color
  - name: defaultReflectionResolution
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: flareFadeSpeed
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: flareStrength
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: fog
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: boolean
  - name: fogColor
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: DataType.Color
  - name: fogDensity
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: fogEndDistance
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: fogStartDistance
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: haloStrength
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: reflectionBounces
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: reflectionIntensity
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: number
  - name: skybox
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: Class.Material
  - name: subtractiveShadowColor
    summary:
    description:
    is_static: false
    code_samples:
    tags:
      - ClientOnly
    type: DataType.Color
methods:
math_operations:
